import { PaletteType } from "@/types/index.ts";

export const errorLensColors = (palette: PaletteType) => ({
  "errorLens.errorBackground": palette.status.errorA[4],
  "errorLens.errorMessageBackground": palette.status.errorA[5],
  "errorLens.errorBackgroundLight": palette.status.errorA[6],
  "errorLens.errorForeground": palette.status.error[11],
  "errorLens.errorForegroundLight": palette.status.error[12],
  "errorLens.warningBackground": palette.status.warningA[4],
  "errorLens.warningMessageBackground": palette.status.warningA[5],
  "errorLens.warningBackgroundLight": palette.status.warningA[6],
  "errorLens.warningForeground": palette.status.warning[11],
  "errorLens.warningForegroundLight": palette.status.warning[12],
  "errorLens.infoBackground": palette.status.infoA[4],
  "errorLens.infoMessageBackground": palette.status.infoA[5],
  "errorLens.infoBackgroundLight": palette.status.infoA[6],
  "errorLens.infoForeground": palette.status.info[11],
  "errorLens.infoForegroundLight": palette.status.info[12],
  "errorLens.hintBackground": palette.status.hintA[4],
  "errorLens.hintMessageBackground": palette.status.hintA[5],
  "errorLens.hintBackgroundLight": palette.status.hintA[6],
  "errorLens.hintForeground": palette.status.hint[11],
  "errorLens.hintForegroundLight": palette.status.hint[12],
  "errorLens.statusBarIconErrorForeground": palette.status.error[8],
  "errorLens.statusBarIconWarningForeground": palette.status.warning[8],
  "errorLens.statusBarErrorForeground": palette.status.error[11],
  "errorLens.statusBarWarningForeground": palette.status.warning[11],
  "errorLens.statusBarInfoForeground": palette.status.info[11],
  "errorLens.statusBarHintForeground": palette.status.hint[11],
});
